### ISSUE TITLE
Direct song links

### ISSUE THREAD

**Issue by doyousketch2** [wothke/websid#5]
I would link others to your site, by way of Twitter, more often,  
if there was a simple way to share a link to a song.  

For example:  
http://www.wothke.ch/tinyrsid/MUSICIANS/T/Tel_Jeroen/RoboCop_3.sid

**Comment by wothke** [comment]
Individual songs can be directly invoked using the following syntax:  http://www.wothke.ch/tinyrsid/index.php/explorer?hvscSong=/MUSICIANS/S/Stinsen/Running_on_Empty.sid;0

New feature: Respective sharing (FB, Twitter, Google+) can now be directly triggered by 
right-clicking on an individual song in the "playlist". In order to share a song found
in the HVSC tree it first needs to be dragged into the "playlist" - for multi-track songs
this allows to then select the specific track to be played (there is no need to store the playlist - it is just used as a temporary tool for track selection).

**Comment by doyousketch2** [comment]
Ty.
