### ISSUE TITLE
Build error: BINARYEN_TRAP_MODE is not supported by the LLVM wasm backed

### ISSUE THREAD

**Issue by ghost** [wothke/websid#7]
Hi,

When I try to build on Windows using the latest version of emscripten, I get the error message in the title. Any advice appreciated. Thanks!

**Comment by wothke** [comment]
It seems the default backend that emscripten uses to generate WASM has been replaced - see: https://emscripten.org/docs/compiling/WebAssembly.html#backends

The new "upstream" backend no longer uses the BINARYEN_TRAP_MODE option. 

I currently don't have the time to update my build env and properly regression test it, but I guess you could try one of the following approaches:

1) just remove the respective "-s BINARYEN_TRAP_MODE='clamp'" option from the build command in makeEmscripten.bat - this should be the preferred approach since the new backend supposedly produces faster and smaller code (ideally it should work with the defaults used by the new backend; if it doesn't you might try to add "-mnontrapping-fptoint" instead).

2) You might just disable WASM output and generate asm.js instead by setting "-s WASM=0" 

3) You could reconfigure your emscripten environment to still use the old "fastcomp" backend (as a last resort in case there still might be issues with the new backend - which is unlikely).

**Comment by ghost** [comment]
Thank you. Removing the option from the build command does get me further. After that, Python seems to run for a very long time. I'm not sure if it's stalled, but I gave up after 15 minutes or so.

**Comment by wothke** [comment]
Do you have other WASM test cases that you have built successfully in your environment? Or did you try the above approach 2 yet?

**Comment by ghost** [comment]
No, this is my first time working with emscripten. I guess that something is wrong with my environment. I tried approach 2 and had the same issue (Python process never seems to finish).

**Comment by wothke** [comment]
Good luck with the emscripten setup then. I'd recommend using the "emsdk" tool approach - see:  https://emscripten.org/docs/getting_started/downloads.html 
Make sure you also have a suitable Java SDK installed - since my makefile actually uses the closure compiler.

Once emscripten has been installed you should first start with the hello-world example from: https://emscripten.org/docs/getting_started/Tutorial.html to verify that your environment is good.

**Comment by ghost** [comment]
Thanks for the support. I will keep trying.

Is there a pre-built version available? Mostly I just want to experiment with using your emulator, not hacking on it at this point?

**Comment by ghost** [comment]
Sorry for multiple messages. I see that I should be able to use the build output in htdocs. I was hoping the API would allow low level control of the SID chip, but looks like the API is mostly for loading, playing and visualizing .sid files right?

**Comment by wothke** [comment]
Yes, that's correct. 

Technically it would not be a problem to add some "write SID register" API (see existing "read" API). You'd just have to also load/play some "dummy endless loop" .sid file to keep the emulator busy (just make sure to disable the default 5-secs "silence detection" in the .js scriptnodeplayer). Any "manual" SID register writes would then result in respective audio output. For "simple" applications this should work (e.g.  UI controls/keyboard to let user manipulate SID).

However, whatever settings you make will be used at least for the duration of a complete WebAudio output buffer (i.e. you might want to use a small buffer to reduce lag - but there will always be some small lag left due to the way WebAudio works). Note: You'd not be able to create the kind of music effects that original C64 composers achieved by quickly switching between SID different settings (you don't get that level of timing control with the typical web "animation frame" triggers).

**Comment by ghost** [comment]
Thanks again, that makes sense. I'm using jssid for now in my project, but I'll probably try to switch to WebSID in future.

**Comment by wothke** [comment]
PS: I have meanwhile added a little callback API that is invoked for every 20ms of generated audio-samples, i.e. it allows you to change SID settings similar to what a single-speed PAL song would typically do (i.e. call some player routine 50 times a second). An example for how that can be used from the JavaScript side can be found here: https://www.wothke.ch/websidStudio/
